import asyncio
import logging
import re
from typing import Optional
from ..infrastructure.exchange.connector import get_paginated_emails, get_email_details, save_draft, mark_as_read, delete_email
from ..infrastructure.database.postgres import (
    delete_email_db,
    get_active_mail_profile,
    get_email_detail_db,
    get_emails_from_db,
    update_email_status,
    upsert_email,
)
from ..domain.ai.responder import AIResponder
from ..domain.knowledge.embedder import search_knowledge
from ..app_state import app_state

logger = logging.getLogger("EmailService")


def _extract_display_name(raw_sender: str) -> str:
    """Extract a readable contact name from common sender formats."""
    if not raw_sender:
        return "cliente"

    sender = raw_sender.strip()

    # Format: Name <mail@domain.com>
    angle_match = re.match(r"^\s*([^<]+)\s*<[^>]+>\s*$", sender)
    if angle_match:
        sender = angle_match.group(1).strip(' "\'')

    # If it's an email, use local-part as a fallback display name
    if "@" in sender:
        sender = sender.split("@", 1)[0]

    sender = sender.replace(".", " ").replace("_", " ").strip()
    if not sender:
        return "cliente"

    return " ".join(word.capitalize() for word in sender.split())


def _normalize_ai_response(ai_response: str, sender_name: str, profile_name: str) -> str:
    """Force greeting/signature ownership to avoid name confusion in generated drafts."""
    if not ai_response:
        return ai_response

    lines = [line.rstrip() for line in ai_response.splitlines()]

    # Remove leading salutations generated by the model so we can enforce the correct addressee.
    salutation_re = re.compile(r"^\s*(hola|estimad[oa]|buen[oa]s\s+d[ií]as|buenas\s+tardes|buenas\s+noches)\b", re.IGNORECASE)
    while lines and (not lines[0].strip() or salutation_re.match(lines[0])):
        lines.pop(0)

    # Drop common signature blocks at the end to enforce the active profile as signer.
    signoff_re = re.compile(r"^\s*(atentamente|saludos|cordialmente|muchas\s+gracias|gracias)\b", re.IGNORECASE)
    for idx in range(len(lines) - 1, -1, -1):
        if signoff_re.match(lines[idx]):
            lines = lines[:idx]
            break

    body = "\n".join(line for line in lines if line is not None).strip()
    if not body:
        body = "Gracias por tu mensaje. Quedo atento para ayudarte con este tema."

    return (
        f"Estimado/a {sender_name},\n\n"
        f"{body}\n\n"
        f"Atentamente,\n"
        f"{profile_name}"
    )

async def list_emails(offset: int = 0, limit: int = 10):
    """List emails from database with pagination"""
    active_profile = await asyncio.to_thread(get_active_mail_profile)
    profile_id = active_profile.get("id") if active_profile else None
    data = await asyncio.to_thread(get_emails_from_db, offset, limit, profile_id)
    return data

async def get_email_detail(item_id: str):
    """Get email detail from DB or Exchange"""
    detail = await asyncio.to_thread(get_email_detail_db, item_id)
    active_profile = await asyncio.to_thread(get_active_mail_profile)
    profile_id = detail.get("profile_id") if detail else (active_profile.get("id") if active_profile else None)
    
    # If not in DB or body is empty, fetch from Exchange
    if not detail or not detail.get('body'):
        logger.info(f"Fetching body for {item_id} from Exchange")
        exchange_id = detail.get("exchange_id") if detail else item_id
        detail = await asyncio.to_thread(get_email_details, exchange_id, profile_id)
        if detail and profile_id:
            await asyncio.to_thread(upsert_email, detail, profile_id)
            detail = await asyncio.to_thread(get_email_detail_db, f"{profile_id}:{detail['exchange_id']}") or detail
    return detail

async def generate_answer(
    item_id: str,
    custom_prompt: Optional[str] = None,
    language: str = 'es'
) -> dict:
    """Generate AI response for an email using RAG (Retrieval Augmented Generation)"""
    # Get the email
    detail = await get_email_detail(item_id)
    
    if not detail:
        return {"status": "error", "message": "Email not found"}

    profile_id = detail.get("profile_id")
    active_profile = await asyncio.to_thread(get_active_mail_profile)
    profile_name = active_profile.get("name") if active_profile else "Perfil activo"
    sender_name = _extract_display_name(detail.get("sender", ""))
    
    # Search knowledge base for relevant context
    email_content = detail.get('body', '') + " " + detail.get('subject', '')
    knowledge_results = await asyncio.to_thread(search_knowledge, email_content, top_k=3)
    
    # Build context from knowledge base
    context_text = ""
    if knowledge_results:
        logger.info(f"Found {len(knowledge_results)} relevant knowledge fragments")
        context_text = "\n\nCONTEXTO DE LA BASE DE CONOCIMIENTO:\n"
        for idx, (content, filename, similarity) in enumerate(knowledge_results, 1):
            context_text += f"\n[Documento {idx}: {filename} - Relevancia: {similarity:.2f}]\n{content}\n"
    else:
        logger.info("No relevant knowledge found in database")
    
    # Prepare prompt
    ai = AIResponder()
    instructions = custom_prompt or "Responde de forma profesional, cordial y breve."
    
    lang_text = {
        "es": "español",
        "en": "inglés",
        "both": "español e inglés (ambos)"
    }.get(language, "español")

    raw_prompt = (
        f"CONTEXTO DE ROL: Eres {profile_name}. Estas redactando una respuesta al remitente del correo.\n"
        f"REGLAS DE RESPUESTA:\n"
        f"1) Saluda al remitente por su nombre: {sender_name}.\n"
        f"2) Firma SIEMPRE con el nombre del perfil activo: {profile_name}.\n"
        f"3) NUNCA firmes con el nombre del remitente ni copies la firma del correo original.\n"
        f"TAREA: Escribir respuesta en {lang_text}.\n"
        f"INSTRUCCIÓN: {instructions}\n"
        f"{context_text}\n"
        f"CORREO DE {detail['sender']} (nombre remitente: {sender_name}):\n"
        f"{detail.get('body', '')}"
    )

    # Update dashboard state
    app_state["current_email"] = {
        "subject": detail["subject"],
        "sender": detail["sender"],
        "date": detail["date"],
        "profile": profile_name,
    }
    app_state["status"] = "Generando respuesta con RAG..."

    # Generate response
    ai_response = await asyncio.to_thread(ai.generate_response, raw_prompt, 'generation')
    
    # Save to DB
    if ai_response:
        ai_response = _normalize_ai_response(ai_response, sender_name, profile_name)
        await asyncio.to_thread(update_email_status, item_id, 'PROCESADO', ai_response)
        app_state["emails_processed"] += 1
    else:
        app_state["current_email"] = None
        app_state["status"] = "Error generando respuesta"
        return {"status": "error", "message": "No se pudo generar respuesta", "ai_response": None}
        
    app_state["current_email"] = None
    app_state["status"] = "En espera (Dashboard)"
        
    return {"status": "success", "ai_response": ai_response}

async def save_draft_email(item_id: str, body: str):
    """Save email draft"""
    if not body:
        return {"status": "error", "message": "No body provided"}
    
    detail = await asyncio.to_thread(get_email_detail_db, item_id)
    profile_id = detail.get("profile_id") if detail else None
    exchange_id = detail.get("exchange_id") if detail else item_id
    success = await asyncio.to_thread(save_draft, exchange_id, body, profile_id)
    return {"status": "success" if success else "error"}

async def mark_email_as_read(item_id: str, read: bool = True):
    """Mark email as read/unread"""
    detail = await asyncio.to_thread(get_email_detail_db, item_id)
    profile_id = detail.get("profile_id") if detail else None
    exchange_id = detail.get("exchange_id") if detail else item_id
    success = await asyncio.to_thread(mark_as_read, exchange_id, read, profile_id)
    return {"status": "success" if success else "error"}

async def delete_email_async(item_id: str):
    """Delete email from both Exchange and local DB"""
    detail = await asyncio.to_thread(get_email_detail_db, item_id)
    profile_id = detail.get("profile_id") if detail else None
    exchange_id = detail.get("exchange_id") if detail else item_id
    success_ex = await asyncio.to_thread(delete_email, exchange_id, profile_id)
    success_db = await asyncio.to_thread(delete_email_db, item_id, profile_id)
    
    return {"status": "success" if (success_ex and success_db) else "partial_success"}
